import type { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const slug = String(ctx.params?.slug || "");
  const base = process.env.NEXT_PUBLIC_SITE_URL || "https://gambitbuilds.com";
  const res = await fetch(`${base}/concepts/${slug}.json`);

  if (!res.ok) return { notFound: true };

  const data = await res.json();
  return { props: { data } };
};

export default function Concept({ data }: any) {
  return (
    <main style={{ fontFamily: "system-ui", padding: 32, maxWidth: 900, margin: "0 auto" }}>
      <h1>{data.headline ?? data.business ?? "Concept"}</h1>
      {data.subheadline ? <p>{data.subheadline}</p> : null}

      <div style={{ marginTop: 16 }}>
        <strong>Call:</strong> {data.phone ?? "—"}
        {data.cta ? <span style={{ marginLeft: 12 }}>• {data.cta}</span> : null}
      </div>

      {Array.isArray(data.services) && data.services.length > 0 ? (
        <>
          <h2 style={{ marginTop: 24 }}>Services</h2>
          <ul>
            {data.services.map((s: string, i: number) => (
              <li key={i}>{s}</li>
            ))}
          </ul>
        </>
      ) : null}

      <p style={{ marginTop: 40, fontSize: 12, opacity: 0.7 }}>
        Concept design generated by Gambit Builds (not affiliated).
      </p>
    </main>
  );
}
